name: cvproj
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - cloudpickle=1.3.0=py_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37he774522_0
  - dask-core=2.12.0=py_0
  - decorator=4.4.2=py_0
  - freetype=2.9.1=ha9979f8_1
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc14hc45fdbb_0
  - imageio=2.8.0=py_0
  - imutils=0.5.3=py37_1
  - intel-openmp=2020.0=166
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.1.0=py37heaa310e_1
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h64f37c6_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py37h74a9793_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h40b0b35_0
  - openssl=1.1.1=he774522_0
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - py-opencv=3.4.2=py37hc319ecb_0
  - pycparser=2.20=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37ha878b3d_0
  - python=3.7.6=h60c2a47_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda101_cudnn7_0
  - pywavelets=1.1.1=py37he774522_0
  - qt=5.9.7=vc14h73c81de_0
  - scikit-image=0.16.2=py37h47e9c7a_0
  - scipy=1.4.1=py37h9439919_0
  - setuptools=46.0.0=py37_0
  - sip=4.19.13=py37ha925a31_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=he774522_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37hfa6e2cd_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
prefix: C:\Users\Michael\Anaconda3\envs\cvproj

